# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

variables:
  - name: Aplication
    value: 'Crud-Cliente'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g serverless'

- task: CmdLine@2
  inputs:
    script: |
      serverless config credentials -p aws -k $(AWS_ID) -s $(AWS_SK) -o
      serverless deploy
